### PR TITLE
Change GTG checkout to submodule and remove manage_externals

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
This PR includes the following:

1. remove manage_externals package and associated files from UPP for GTG checkout
2. add git submodule to handle GTG checkout

Associated updates are made on the workflow side to update the checkout process to use the submodule for GTG. Here is the build log for the UPP with GTG after testing the clone updates from my fork branch:

```
/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2/sorc/logs/build_ncep_post_test7_gtg.log
```

To test my updates in my fork branch:
```
git clone --recursive -b post_gfsv16_wcoss2 https://github.com/KateFriedman-NOAA/UPP.git gfs_post.fd
```

If you do not use `--recursive` it will NOT invoke the submodule and will NOT clone the GTG.

```
Kate.Friedman@dlogin02:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/UPP> git clone --recursive -b post_gfsv16_wcoss2 https://github.com/KateFriedman-NOAA/UPP.git gfs_post.fd
Cloning into 'gfs_post.fd'...
remote: Enumerating objects: 6580, done.
remote: Counting objects: 100% (1643/1643), done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 6580 (delta 1535), reused 1371 (delta 1370), pack-reused 4937
Receiving objects: 100% (6580/6580), 35.93 MiB | 17.87 MiB/s, done.
Resolving deltas: 100% (4698/4698), done.
Submodule 'sorc/post_gtg.fd' (https://github.com/NCAR/UPP_GTG) registered for path 'sorc/post_gtg.fd'
Cloning into '/lfs/h2/emc/global/noscrub/Kate.Friedman/git/UPP/gfs_post.fd/sorc/post_gtg.fd'...
remote: Enumerating objects: 4000, done.        
remote: Counting objects: 100% (18/18), done.        
remote: Compressing objects: 100% (14/14), done.        
remote: Total 4000 (delta 7), reused 13 (delta 4), pack-reused 3982        
Receiving objects: 100% (4000/4000), 34.69 MiB | 19.10 MiB/s, done.
Resolving deltas: 100% (2761/2761), done.
Submodule path 'sorc/post_gtg.fd': checked out '95959a1c04ef49452186e4be9d49b0c1d7aba7d9'
Kate.Friedman@dlogin02:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/UPP> cd gfs_post.fd/sorc/post_gtg.fd/
Kate.Friedman@dlogin02:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/UPP/gfs_post.fd/sorc/post_gtg.fd> git branch
* (HEAD detached at 95959a1)
  master
Kate.Friedman@dlogin02:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/UPP/gfs_post.fd/sorc/post_gtg.fd> git log -1
commit 95959a1c04ef49452186e4be9d49b0c1d7aba7d9 (HEAD, tag: ncep_post_gtg.v2.0.4, origin/v16)
Author: Yali Mao <yali.mao@noaa.gov>
Date:   Tue Jun 8 06:07:13 2021 +0000

    If GFS input fields are out of bounds, contintue to calcuate GTG and
    output error messages to logfile instead of quitting the program
```

Refs: #420, #363

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA I tested on your branch for gtg code checking out as:
`git clone --recursive -b post_gfsv16_wcoss2 https://github.com/KateFriedman-NOAA/UPP.git gfs_post.fd`
I got failure as:
```
Wen.Meng@dlogin02 kate$ git clone --recursive -b post_gfsv16_wcoss2 https://github.com/KateFriedman-NOAA/UPP.git gfs_post.fd
Cloning into 'gfs_post.fd'...
remote: Enumerating objects: 6580, done.
remote: Counting objects: 100% (1643/1643), done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 6580 (delta 1535), reused 1371 (delta 1370), pack-reused 4937
Receiving objects: 100% (6580/6580), 35.93 MiB | 13.01 MiB/s, done.
Resolving deltas: 100% (4698/4698), done.
Submodule 'sorc/post_gtg.fd' (https://github.com/NCAR/UPP_GTG) registered for path 'sorc/post_gtg.fd'
Cloning into '/lfs/h2/emc/vpppg/noscrub/Wen.Meng/ncep_post/kate/gfs_post.fd/sorc/post_gtg.fd'...
Username for 'https://github.com': WenMeng-NOAA
Password for 'https://WenMeng-NOAA@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/NCAR/UPP_GTG/'
fatal: clone of 'https://github.com/NCAR/UPP_GTG' into submodule path '/lfs/h2/emc/vpppg/noscrub/Wen.Meng/ncep_post/kate/gfs_post.fd/sorc/post_gtg.fd' failed
Failed to clone 'sorc/post_gtg.fd'. Retry scheduled
Cloning into '/lfs/h2/emc/vpppg/noscrub/Wen.Meng/ncep_post/kate/gfs_post.fd/sorc/post_gtg.fd'...
Username for 'https://github.com'
```
It seems I can't use the https url for gtg checking out, but the ssh url is working. Do you know anything is missing on my github account?

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA GitHub deprecated the use of passwords in late summer and so users have to use personal access tokens now. This part of the error gives info on that:

```
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
```

So you need to set up a personal access token in your GitHub account and add it to a new `.git-credentials` file on each HPC you work on. See slides 10 and 11 of this slidedeck for more info:
https://docs.google.com/presentation/d/16XIq0mniV1JjhrxGQ2E00mFpnzd_w9CUnpaY4_Ogi2E/edit#slide=id.g6052c2987b_9_42

Generate a token, add it within a .git-credentials file in your /u/$USER area on Dogwood (and other HPCs), and then try that clone again. Let me know how it goes. With a personal access token in place it won't matter what method you use for cloning, it will use your token like a password and you'll have passwordless git actions (push/pull).

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Your tips work for me. Now I can clone gtg code.  Thanks!

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
Glad it's working for you now @WenMeng-NOAA ! Thanks for approving this PR, please feel free to submit it into your branch now, I don't have a submit button to do it myself.

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA I was able to checkout GTG code successfully and compiled the code without problems. The only issue is GTG repository. GTG is delivered by tags, and the operational one is https://github.com/NCAR/UPP_GTG/tree/ncep_post_gtg.v2.0.3. 
If we checkout https://github.com/NCAR/UPP_GTG, we won't get the exact tag.

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA Please ignore the previous comments. @aerorahul has explained that submodule tracks the hash of the commit.

**Pull request merged**
